---
provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1
    driver:
      name: vagrant
      customize:
        memory: 8192

suites:
  - name: default
    run_list:
      - recipe[test]
